### ISSUE TITLE
What is the latency of sendRequest for sending order?

### ISSUE THREAD

**Issue by akure** [crypto-chassis/ccapi_cpp#50]
What is the latency of sendRequest for sending order to binance test net and main net?

How can I measure the latency order send round trip time in my set up?

**Comment by cryptochassis** [comment]
@akure Using the following code snippet we performed a measurement using a home internet. The result is 0.138s using binance's test server and 0.141s using binance's production server. Notice that the numbers should depend on the network speed: if your server is co-located with binance's exchange server, the latency will be smaller. Therefore I think you can do two experiments in practice:
a. Change the location of your server and use the same code. Compare to see which location is best (probably Binance's server is located somewhere in Asia).
b. Fix the location of your server and use different code (i.e. another library). Compare to see which library is best.
Let us know if you have more questions.

```
    Session session(sessionOptions, sessionConfigs);
    Queue<Event> eventQueue;
    int total = 20;
    float microseconds = 0;
    for (int i = 0; i < total; i++) {
      Request request(Request::Operation::CREATE_ORDER, "binance", "BTCUSDT");
      request.appendParam({
        {"SIDE", "BUY"},
        {"QUANTITY", "0.0005"},
        {"LIMIT_PRICE", "20000"}
      });
      auto start = std::chrono::high_resolution_clock::now();
      session.sendRequest(request, &eventQueue);
      auto stop = std::chrono::high_resolution_clock::now();
      microseconds += std::chrono::duration_cast<std::chrono::microseconds>(stop - start).count();
      std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }
    std::cout << "average latency is " + std::to_string(microseconds / total) + "microseconds" << std::endl;
```

**Comment by akure** [comment]
Thanks,

Does Binance colocation actually means , it is located in the same server room of Binance. 
Does Binance really support this?

**Comment by cryptochassis** [comment]
You're welcome. Binance has an article about colocation: https://academy.binance.com/en/glossary/colocation. It probably isn't the same server room, but generally the same data center. I'm not sure whether Binance offers it or not, but do know that there are a couple of exchanges offering it: one prominent example is Gemini. See https://www.gemini.com/institutions.

> Gemini's primary trading platform and network point of presence (PoP) is housed in the Equinix NY5 data center in Secaucus, New Jersey. Customers can cross connect from their NY2/NY4/NY5 infrastructure or use an approved extranet provider to access Gemini production Market Data feeds, Drop Copy, and Order Entry sessions.

**Comment by cryptochassis** [comment]
Need to mention that the above numbers were produced without performance tuning. The speed up can be significant with performance tuning: https://github.com/crypto-chassis/ccapi/tree/v3.0.6#performance-tuning.
